version: '3.8'

services:
  vending-hub-web:
    image: vending-admin-hub
    build: .
    container_name: vending-admin-container
    restart: always
    ports:
      - "8080:80"
    expose:
      - "80"